### ISSUE TITLE
Some videos are missing

### ISSUE THREAD

**Issue by owang** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#1]
Running `./scripts/getData.sh` generates a lot of responses like the following:

```
--2017-09-13 16:47:05--  http://domedb.perception.cs.cmu.edu/webdata/dataset/141217_pose1/videos/vga_shared_crf10/vga_14_03.mp4
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.177.92
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.177.92|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-13 16:47:05 ERROR 404: Not Found.
```

**Comment by behinduiam** [comment]
I meet the same problem too. Any solution?

**Comment by jhugestar** [comment]
Hi,

Those sequences have camera failures during the capture at the moment, and the missing files means we lost those views.  

By the way, we plan to have a major update of our dataset soon with many new sequences.  I hope this can be helpful for you.
