### ISSUE TITLE
Total Capture

### ISSUE THREAD

**Issue by Kernelux** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#10]
Hi!
I hope you are doing great and once again thanks for your work!
I was wondering if you were planning to release some meshes based on your "Total Capture" paper for some of the scenes or trained Frankestein/Adam models ?

Thanks!

**Comment by jhugestar** [comment]
Hi, 
Sorry for my delayed response. We are currently working on this, and hope to release the models and output meshes fitted to the data. Perhaps it will take a couple of months.

**Comment by ryohachiuma** [comment]
Any update on this?

**Comment by jhugestar** [comment]
The Adam model has been released as a part of our recent work: 

http://domedb.perception.cs.cmu.edu/mtc.html

https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture
