### ISSUE TITLE
ksynctables_161202_haggling1.json is missing

### ISSUE THREAD

**Issue by GuyTevet** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#13]
Hi,
First, Thanks a lot for your magnificent work.

It seems that the file ksynctables_161202_haggling1.json is missing while running ./scripts/getData_kinoptic.sh

--2018-12-19 16:51:47--  http://domedb.perception.cs.cmu.edu/webdata/dataset/161202_haggling1/kinect_shared_depth/ksynctables.json
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.177.92
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.177.92|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-19 16:51:48 ERROR 404: Not Found.

**Comment by jhugestar** [comment]
I have fixed the issue, and the file should be downloadable now. 
Please reopen this issue if you have the same problem.
