### ISSUE TITLE
COCO19 Keypoint Mapping

### ISSUE THREAD

**Issue by chiragraman** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#16]
Hello!

Thanks for your work! With the update to the COCO19 keypoints, I believe the mapping in the doc is outdated, and no longer supported. Is there an updated mapping available?

The closest I could find is the 18 Keypoints over on OpenPose (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/media/keypoints_pose_18.png), and I imagine the 19th is the mean of the two hip joints. 

Before I manually figure out the indices from the `joints19` array, I just wanted to ask if there is one readily available. 

Thanks again!

**Comment by jhugestar** [comment]
Hi,

The order should be:

0: Neck
1: Nose
2: BodyCenter (center of hips)
3: lShoulder
4: lElbow
5: lWrist,
6: lHip
7: lKnee
8: lAnkle
9: rShoulder
10: rElbow
11: rWrist
12: rHip
13: rKnee
14: rAnkle
15: rEye
16: lEye
17: rEar
18: lEar

Please reopen this issue, if this is incorrect. 

Thanks,
Han

**Comment by chiragraman** [comment]
Thanks @jhugestar!

Also I see you updated the doc as well, thanks for that.

**Comment by mostafamoradipour** [comment]
Hi,

The order should be:

0: Neck
1: Nose
2: BodyCenter (center of hips)
3: lShoulder
4: lElbow
5: lWrist,
6: lHip
7: lKnee
8: lAnkle
9: rShoulder
10: rElbow
11: rWrist
12: rHip
13: rKnee
14: rAnkle
15: lEye
16: lEar
17: rEye
18: rEar

Thanks,
Mostafa
