### ISSUE TITLE
The problem of demo_kinoptic_gen_ptcloud.m

### ISSUE THREAD

**Issue by postgraduater** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#2]
demo_kinoptic_gen_ptcloud.m
When the above program is executed, hints appear on the screen as follows:
PLY files will be saved in: F:/panoptic-toolbox/matlab/160422_haggling1/kinoptic_ptclouds
hd_index: 102, UnivTime: 44295.918
idk: 1, -1661.1570
Skipping 1
idk: 2, -1668.9130
Skipping 2.776500e+01, depth-color diff idk: 3, -1641.4520
Skipping 3
idk: 4, -1645.5540
Skipping 4
idk: 5, -1635.2900
Skipping 5
idk: 6, -1664.9270
Skipping 2.665800e+01, depth-color diff idk: 7, -1635.9900
Skipping 7
idk: 8, -1635.0910
Skipping 8
idk: 9, -1664.5840
Skipping 2.658900e+01, depth-color diff idk: 10, -1657.6420
Skipping 10
But when I open the folder F:/panoptic-toolbox/matlab/160422_haggling1/kinoptic_ptclouds
I found that This folder is empty, and there is no PLY file.

So what's the problem? How to modify the problem? Thank you!

**Comment by jhugestar** [comment]
Thank you for your interest. Actually, we haven't officially released this although we push the instruction in the git. I am happy that you already tried this, though. 

It seems like the code stops generations and escaped the loop since the frame is not valid for the sequences. Can you change the frame range (increase the start frame index) and try again?

**Comment by postgraduater** [comment]
for demo_kinoptic_gen_ptcloud.m
if **hd_index_list= 5:9**;      When the above program is executed, hints appear on the screen as follows:
PLY files will be saved in: F:/panoptic-toolbox/matlab/160422_haggling1/kinoptic_ptclouds
hd_index: 7, UnivTime: 41126.054
idk: 1, -4831.0210
Skipping 1
idk: 2, -4838.7770
Skipping 2.776500e+01, depth-color diff idk: 3, -4811.3160
Skipping 3
idk: 4, -4815.4180
Skipping 4
idk: 5, -4805.1540
Skipping 5
idk: 6, -4834.7910
Skipping 2.665800e+01, depth-color diff idk: 7, -4805.8540
Skipping 7
idk: 8, -4804.9550
Skipping 8
idk: 9, -4834.4480
Skipping 2.658900e+01, depth-color diff idk: 10, -4827.5060
Skipping 10
But when I open the folder F:/panoptic-toolbox/matlab/160422_haggling1/kinoptic_ptclouds
I found that This folder is still empty, and there is no PLY file.

**Comment by jhugestar** [comment]
Yes, please try to increase the hd_index_list number, for example, hd_index: 1000.
