### ISSUE TITLE
Depth images

### ISSUE THREAD

**Issue by erezposner** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#20]
Hi, Im trying to download the kinect depth maps.
I followed http://domedb.perception.cs.cmu.edu/171204_pose1.html using /getData.sh 171204_pose1 but the command doesn't download the depth maps.

How can I Download all data from kinect sensors. 
Thanks

**Comment by v0lta** [comment]
I have a similar problem running getData_kinoptic.sh returns:

kinectVideos/kinect_50_01.mp4                                                                                                                 
wget -c -O kinectVideos/kinect_50_01.mp4 http://domedb.perception.cs.cmu.edu/webdata/dataset/sampleData/videos/kinect_shared_crf20/sampleData_kinect1.mp4 || rm -v kinectVideos/kinect_50_01.mp4                                                                                            
--2019-07-16 15:11:41--  http://domedb.perception.cs.cmu.edu/webdata/dataset/sampleData/videos/kinect_shared_crf20/sampleData_kinect1.mp4     
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.177.92                                                         
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.177.92|:80... connected.                                      
HTTP request sent, awaiting response... 404 Not Found                                                                                         
2019-07-16 15:11:41 ERROR 404: Not Found.

**Comment by v0lta** [comment]
For posterity getDB_ptCloud_ver1.sh seems to work.

**Comment by jhugestar** [comment]
@erezposner Hi, sorry for my late reply. "getData.sh" is for Panoptic Dataset (VGA+HD+3D skeletons), which is different from Kinoptic (RGB+D, skeletons). Use "getData_kinoptic.sh" for Kinect data. For example. 

scripts/getData_kinoptic.sh 171204_pose1

**Comment by jhugestar** [comment]
@v0lta "sampleData" is for Panoptic Dataset (VGA+HD+3D skeletons), which does not have Kinect data samples (sorry, I know these are confusing). You are right, use the "getDB_ptCloud_ver1.sh" and see the available sequences in the script.
