### ISSUE TITLE
Sensor information

### ISSUE THREAD

**Issue by A7ocin** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#21]
Hello, thank you for the nice toolbox.
I would like to have some more information about the dataset, in particular either the HD camera/sensor model(s) or the sensor size in millimeters. 
Since I didn't find them in the paper, is it possible to know them? Thank you kindly

**Comment by jhugestar** [comment]
Hi, Thanks for your interest. 

Our HD data is captured by "Canon XH G1s High Definition camcorder".

**Comment by A7ocin** [comment]
Hi, thank you for the fast response. Can you also tell me the focal length used for recording the videos? Thank you
