### ISSUE TITLE
Does anyone have the transcripts and speaker ID annotations?

### ISSUE THREAD

**Issue by steph-tan** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#22]
The website said that "they will be available soon". Are these hidden somewhere that I didn't manage to find, or were they not yet released?

**Comment by ozzyou** [comment]
Do you happen to have found this already @paperclipt?

**Comment by jhugestar** [comment]
Sorry for the delay. Please check below:

https://github.com/CMU-Perceptual-Computing-Lab/ssp
