### ISSUE TITLE
Speaking status annotations missing

### ISSUE THREAD

**Issue by ozzyou** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#24]
I was wondering whether the speaking status annotations in the haggling scenes could be published. I'm unable to do it myself, as I can't easily match the annotations in "univTime" for the body3DScene measurements with my annotations based on the video recording time.

**Comment by jhugestar** [comment]
We recently have released the processed data with the speaking annotations. Please check below:

https://github.com/CMU-Perceptual-Computing-Lab/ssp
