### ISSUE TITLE
Keypoint order in annotation

### ISSUE THREAD

**Issue by elmuz** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#26]
It seems to me that there is an error in README about the order of kpts annotation.
I think you used the following:
        0: "Neck",
        1: "Nose",
        2: "MidHip",
        3: "LShoulder",
        4: "LElbow",
        5: "LWrist",
        6: "LHip",
        7: "LKnee",
        8: "LAnkle",
        9: "RShoulder",
        10: "RElbow",
        11: "RWrist",
        12: "RHip",
        13: "RKnee",
        14: "RAnkle",
        15: "LEye",
        16: "LEar",
        17: "REye",
        18: "REar",

**Comment by RSKothari** [comment]
I experienced the same issue: https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox/issues/34

**Comment by jhugestar** [comment]
Thanks! I have fixed the readme.
