### ISSUE TITLE
I found a typo in example.ipynb

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#3]
At In [5] : I think that the first line "vga_skel_json_path = data_path+seq_name+'/hdPose3d_stage1/'" is typo. 

The variable name "vga_skel_json_path" should be changed to "hd_skel_json_path".

Thank you for making this program. 

Have a good time.

**Comment by jhugestar** [comment]
Thank you for letting us know. We will fix it in our next update.
