### ISSUE TITLE
tar file download is empty once opened in one of the downloads from getData.sh

### ISSUE THREAD

**Issue by Emnolope** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#32]
hdPose3d_stage1_coco19.tar is empty in 60422_haggling1.

The tar file takes up 3.8MB on hard disk space, but open opening, it is empty.
I am making this an issue as it may be indicative of a larger problem.
![image](https://user-images.githubusercontent.com/44859532/81630298-12648880-93ba-11ea-896b-b08bd5cb62de.png)

**Comment by Emnolope** [comment]
body3dScene_00001940.json is missing from hdPose3d_stage1_coco19.tar in 160906_band1 .
and
body3DScene_00013740.json is missing from hdPose3d_stage1_coco19.tar in 160422_haggling1

**Comment by jhugestar** [comment]
3.8MB should be not the correct one. It should be bigger. Can you remove them and rerun the download script? I suspect it failed in downloading in your first trial (making the black file), and when you retry it, the script will not download it because there exists a file with the same name already.

**Comment by Emnolope** [comment]
Yee, it was my issue. It was incomplete download totally cool, closing.
