### ISSUE TITLE
Potentially incorrect joint labels in `170228_haggling_a2`

### ISSUE THREAD

**Issue by RSKothari** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#34]
https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox

Hello, 

The skeleton definitions for the left and right eyes and ears do not quite match up with what you've started in your repo. Is there another format I should be considering for `hdPose3d_stage1_coco19`?

From my understanding, the ordering is as follows:

'''
    0: Neck
    1: Nose
    2: BodyCenter (center of hips)
    3: lShoulder
    4: lElbow
    5: lWrist,
    6: lHip
    7: lKnee
    8: lAnkle
    9: rShoulder
    10: rElbow
    11: rWrist
    12: rHip
    13: rKnee
    14: rAnkle
    15: lEye
    16: lEar
    17: rEye
    18: rEar
'''

**Comment by RSKothari** [comment]
Actually I'm quite certain now. The 3D joint labels do not match the description provided. I wonder if this discrepancy is localized to this particular example or is it a global thing. I'll email the authors to double check as it could impact other works.

**Comment by jhugestar** [comment]
Thanks for reporting this!  Let me double check it and update the readme. 

Just a clarification question: have you found that the orders are not consistent across sequences, or skeleton orders are consistent and we only need to fix our readme description?

**Comment by RSKothari** [comment]
From the two examples that I've been playing with, it seems the readme description is incorrect. However, I would check all sequences to be sure. Just wanted to bring to your notice.

**Comment by RSKothari** [comment]
Hello, @jhugestar do you have any updates on if this is an error in the documentation or a bug in the dataset somewhere?

**Comment by jhugestar** [comment]
Thanks for pointing this out. The dataset looks correct and this was just a readme error. I have updated it!
