### ISSUE TITLE
failed: Connection timed out

### ISSUE THREAD

**Issue by zhangyahu1** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#37]
I try to download the dataset but fail to connect http://domedb.perception.cs.cmu.edu/
Is it because the website is under maintenance?

**Comment by zj-dong** [comment]
I also have this issue and can't open the website.

**Comment by b-wang** [comment]
Same here, the website seems to be down for a few days.

**Comment by angechen** [comment]
How long will the website be down?

**Comment by jhugestar** [comment]
Sorry for the inconvenience. Our server has been offline due to power cut at CMU, and Covid-19 makes it difficult to access the campus. We will turn on the server asap.
