### ISSUE TITLE
website problem

### ISSUE THREAD

**Issue by lisa676** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#38]
We are facing problem to download the datasets because website is not working.

**Comment by QuteSaltyFish** [comment]
Have you find a way to get the dataset yet?

**Comment by wangsen1312** [comment]
same problem

**Comment by Svito-zar** [comment]
same problem for me

**Comment by jhugestar** [comment]
Sorry for the inconvenience. Our server has been offline due to power cut at CMU, and Covid-19 makes it difficult to access the campus. We will turn on the server asap.

**Comment by lisa676** [comment]
@QuteSaltyFish  no I'm unable to find any solution.

@jhugestar  Thanks for this update. Looking forward for server to come on working stage.

**Comment by nicolasugrinovic** [comment]
@jhugestar Thank you for the clarification, any news on this?

**Comment by jhugestar** [comment]
Hi all, 

Sorry for the long delay. The issue has been resolved and our sever is online now.

Kudos to @xiangdonglai !
