### ISSUE TITLE
Missing joints on point cloud db

### ISSUE THREAD

**Issue by Kernelux** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#4]
Hi!
First of all, thank you so much for this amazing dataset! The amount of work you guys put in it seems crazy.
With the recent released of the depth data I could not get happier!
But it seems that there is some issue. 
The script to get the depths works properly, however, retrieving the joints information for those scenes does not work for every scene.
The scene with no joints information at all are:

- 160226_ultimatum1
- 160317_moonbaby1
- 160317_moonbaby2
- 160317_moonbaby3
- 170307_dance2
- 170307_dance3
- 170307_dance4
- 170307_dance6
- 170915_toddler2
- 170915_toddler3
- 170915_toddler4
- 171026_cello1
- 171026_cello2
- 171026_pose2
- 171204_pose1
- 171204_pose2
- 171204_pose3
- 171204_pose4
- 171204_pose5
- 171204_pose6

Moreover, it seems that some of the available scenes only have either the coco19 joints or the "joints15".
I can provide the list if needed to.
Another question regarding those joints, what is the difference between the coco19 joints and the joints_15 except for the number of joints?

Thanks for your help!

**Comment by jhugestar** [comment]
Hi, thank you for your interest. Current release only considers multiple kinect part and point cloud dataset, and the skeleton part has not been officially released yet, although you can still get them for some old sequences. We plan to release the corresponding skeletons soon. Stay tuned!
