### ISSUE TITLE
annotation of skeletopn key-points

### ISSUE THREAD

**Issue by arnitkun** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#5]
How did you guys annotated the extracted frames? I mean if there was some specific tool or a proprietary method or something else.

I didn't knew where to ask this.Sorry.

**Comment by jhugestar** [comment]
If what you mean by annotation is the 3D keypoints, we run 2D keypoint detections for each view and run 3D reconstruction to combine the cues from multiple views. Please see our paper:

https://arxiv.org/abs/1612.03153
