### ISSUE TITLE
Calibration Problem

### ISSUE THREAD

**Issue by chjXu** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#61]
hello, i have some question about this calibration file. 
1. how to calculate the R matrix and t vector when the calibration file is created? 
2. All cameras are represented by the same one world coordinate?

i do a experiment about this camera transformation in the "171204_pose1_sample" dataset. 
And I get this result as follows
![Screenshot from 2021-11-24 21-08-59](https://user-images.githubusercontent.com/52600391/143244442-08237efd-baf2-4119-9a22-b008ade38bf1.png)
.
![Screenshot from 2021-11-24 21-09-09](https://user-images.githubusercontent.com/52600391/143244460-244fefeb-f98b-4dda-ac86-26a633a6f006.png)

The results are wrong, right?

If necessary, I can upload my test code.

**Comment by MikeAiJF** [comment]
Hello, are you calibrating multiple cameras?
