### ISSUE TITLE
Script returns "404 Not Found" when trying to download keypoint data

### ISSUE THREAD

**Issue by thully** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#7]
When attempting to use the getData.sh script to download data, a "404 Not Found" error is returned for the keypoint data files (including hdPose3d, hdHand3d, and hdFoot3d). This happens with the sampleData dataset and every other data set I tested. The videos download fine.

If I revert the getData.sh script to a version from a week ago (undoing the last change), I do get a hdPose3d_stage1.tar (which is no longer downloaded by the new script), but the hdPose3d_stage1_coco19.tar returns a 404 Not Found error.

The errors are as follows:

--2018-07-19 16:27:34--  http://domedb.perception.cs.cmu.edu/webdata/dataset/sampleData/hdPose3d_stage1_coco19.tar
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.177.92
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.177.92|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-19 16:27:34 ERROR 404: Not Found.

rm: hdPose3d_stage1_coco19.tar: No such file or directory
--2018-07-19 16:27:34--  http://domedb.perception.cs.cmu.edu/webdata/dataset/sampleData/hdFace3d.tar
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.177.92
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.177.92|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-19 16:27:34 ERROR 404: Not Found.

rm: hdFace3d.tar: No such file or directory
--2018-07-19 16:27:34--  http://domedb.perception.cs.cmu.edu/webdata/dataset/sampleData/hdHand3d.tar
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.177.92
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.177.92|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-19 16:27:34 ERROR 404: Not Found.

rm: hdHand3d.tar: No such file or directory

**Comment by bucktoothsir** [comment]
have you solved this problem?

**Comment by hyli2020** [comment]
Same bug here.

**Comment by jhugestar** [comment]
Hi guys, sorry for my late reply. 

hdPose3d_stage1.tar is a outdated format (following MPI joint hierarchy), so we decided not support this anymore, although there are some sequences where still this data is available.

The "404 Not Found..." message basically mean that there is no such data in our server to be shared. In some case, the data is not ready, and in other cases, I mistakenly removed them, which should be fixed. 

For the sample data, I will check it and let you know asap.

**Comment by feiwangoooh** [comment]
> Hi guys, sorry for my late reply.
> 
> hdPose3d_stage1.tar is a outdated format (following MPI joint hierarchy), so we decided not support this anymore, although there are some sequences where still this data is available.
> 
> The "404 Not Found..." message basically mean that there is no such data in our server to be shared. In some case, the data is not ready, and in other cases, I mistakenly removed them, which should be fixed.
> 
> For the sample data, I will check it and let you know asap.

eager waiting......

**Comment by jhugestar** [comment]
1. Is wget installed in your machine? Or are you using a Mac which may only have curl?

I have checked this, and it seems like the there exists a bug for curl command option in getData.sh script. The files are there, but previous curl option in the script was wrong. I update the script, so please try it again. 


2. The "sampleData" is indeed an outdated one which does not have face and hand data. Please try with "171204_pose1_sample" sequence:

./scripts/getData.sh 171204_pose1_sample 0 0

Our current document is a bit messy, which I need to clean up asap. 

3. 
Without using the script, you can directly access via the url to download, if there exist files in the server. For example, try to copy and paste the following url in the web browser:

http://domedb.perception.cs.cmu.edu/webdata/dataset/171204_pose1_sample/hdFace3d.tar

If this cannot find the file, that really means the file is missing. Please let me know if this happens for some sequences.

**Comment by hyli2020** [comment]
Hi @jhugestar in the collections (http://domedb.perception.cs.cmu.edu/collections), only two sequences have the annotation files. Others are missing. Could you please have a check? Also, in some webpage, it says the sequence has annotation (http://domedb.perception.cs.cmu.edu/151125_bang.html), but it is actually not. 

I want to create a version of train/val split so that everyone can train and test their algorithms. 

Thanks

**Comment by jhugestar** [comment]
We have updated the list of sequences with 3D keypoint annotations. Please check "getDB_panoptic_ver1_2.sh" for Panoptic DB and "etDB_ptCloud_ver1.sh" for Kinoptic DB (10 RGB+D).
