### ISSUE TITLE
171204_pose1/hdMeshTrack_face.tar data not found 

### ISSUE THREAD

**Issue by arnabdeypolimi** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#83]
I am trying to download the dataset but getting this error 
`--2023-11-16 10:10:06--  http://domedb.perception.cs.cmu.edu/webdata/dataset/171204_pose1/hdMeshTrack_face.tar
Resolving domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)... 128.2.220.8
Connecting to domedb.perception.cs.cmu.edu (domedb.perception.cs.cmu.edu)|128.2.220.8|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-16 10:10:06 ERROR 404: Not Found.
`

**Comment by aidansmyth95** [comment]
What was the resolution for this? Encountering same thing
