### ISSUE TITLE
extractAll.sh doesn't work on macOS without changes

### ISSUE THREAD

**Issue by thully** [CMU-Perceptual-Computing-Lab/panoptic-toolbox#9]
When running the extractAll.sh script on macOS, I get the following error:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path

To resolve this, I had to install the GNU version of readlink (it's in the coreutils Homebrew package), and then change the script to reference greadlink. Perhaps this can be referenced in the readme or worked around in some way.

**Comment by jhugestar** [comment]
Thanks. I have removed the dependency.
